repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
    name: check for added large files
    description: prevents giant files from being committed.
    entry: check-added-large-files
    language: python
    stages: [commit, push, manual]

  - id: check-executables-have-shebangs
    name: check that executables have shebangs
    description: ensures that (non-binary) executables have a shebang.
    entry: check-executables-have-shebangs
    language: python
    types: [text, executable]
    stages: [commit, push, manual]

  - id: check-yaml
    name: check yaml
    description: checks yaml files for parseable syntax.
    entry: check-yaml
    args: ["--allow-multiple-documents"]
    language: python
    exclude: '.ytt.yaml$'
    types: [yaml]


- repo: local
  hooks:
#     - id: shfmt
#       name: shfmt
#       entry: shfmt -w -i 4
#       language: golang
#       additional_dependencies: [mvdan.cc/sh/v3/cmd/shfmt@v3.4.3]
#       types: [shell]

    - id: actionlint
      name: actionlint
      entry: actionlint
      language: golang
      additional_dependencies: [github.com/rhysd/actionlint/cmd/actionlint@v1.6.23]
      types: [yaml]

      files: "^.github/workflows/"
    # FIXME: fails on composite actions
    #      files: "^.github/workflows/|action.yml"



##########
# pre-commit-ci config

ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: weekly
    skip: []
    submodules: false

